version: '3.8'

services:
  ddduniversitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  portainer:
    image: portainer/portainer-ce
    
  papercut:
    image: jijiechen/papercut
    
  redis:
    image: redis

  shopway.app:
    image: ${DOCKER_REGISTRY-}shopwayapp
    build:
      context: .
      dockerfile: src/Shopway.App/Dockerfile

  paymentgateway:
    image: ${DOCKER_REGISTRY-}paymentgateway
    build:
      context: .
      dockerfile: PaymentGateway/Dockerfile

networks:
  db_net:

volumes:
  ddduniversity_volume:
  portainer_volume:  
  papercut_volume:  
