version: '3.8'

services:
  ddduniversitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  shopway.app:
    image: ${DOCKER_REGISTRY-}shopwayapp
    build:
      context: .
      dockerfile: src/Shopway.App/Dockerfile

networks:
  db_net:

volumes:
  ddduniversity_data: