version: '3.9'

services:
  ddduniversitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  portainer:
    image: portainer/portainer-ce
    
  papercut:
    image: jijiechen/papercut
    
  redis:
    image: redis

  shopway.app:
    image: ${DOCKER_REGISTRY-}shopwayapp
    build:
      context: .
      dockerfile: src/Shopway.App/Dockerfile

  paymentgateway:
    image: ${DOCKER_REGISTRY-}paymentgateway
    build:
      context: .
      dockerfile: PaymentGateway/Dockerfile

  opentelemetrycollector:
    image: otel/opentelemetry-collector-contrib

  jaeger:
    image: jaegertracing/all-in-one

  prometheus:
    image: prom/prometheus

  grafana:
    image: grafana/grafana

networks:
  db_net:

volumes:
  ddduniversity_volume:
  portainer_volume:  
  papercut_volume:  
  prometheus_volume:
  grafana_volume:
