version: '3.8'

services:
  ddduniversitydb:
    container_name: ddduniversitydb
    environment:
      - SA_PASSWORD=DDDUniversity1233
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    restart: always
    networks:
      - db_net
    ports:
      - "1434:1433" #external port was modified to 1434, because I have installed SQL Server locally, so the port 1433 is already used
    volumes:
      - ddduniversity_volume:/var/opt/mssql

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data

  papercut:
    container_name: papercut
    restart: unless-stopped
    networks:
      - db_net
    ports:
      - "25:25"
      - "37408:37408"
    volumes:
      - papercut_volume:/Papercut

  redis:
    container_name: redis
    restart: unless-stopped
    networks:
      - db_net
    ports:
      - "6379:6379"

  shopway.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CacheConnection=redis
      - "MailSenderOptions__Host=papercut"
      - "MailSenderOptions__Port=25"
      - "MailSenderOptions__UseSSL=false"
      - "ConnectionStrings__DefaultConnection=Server=ddduniversitydb;Database=DDDUniversity;User Id=sa;Password=DDDUniversity1233;TrustServerCertificate=True;"
      - "ConnectionStrings__TestConnection=Server=ddduniversitydb;Database=DDDUniversityTest;User Id=sa;Password=DDDUniversity1233;TrustServerCertificate=True;"
      - "ASPNETCORE_HTTP_PORTS=80;8080"
    restart: unless-stopped
    networks:
      - db_net
    depends_on:
      - ddduniversitydb
    ports:
      - "8080:80"

  paymentgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
    restart: unless-stopped
    networks:
      - db_net
    ports:
      - "61045:8082"
      - "61046:8083"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
