global:
  evaluation_interval: 30s
  scrape_interval: 10s

scrape_configs:
  - job_name: opentelemetrycollector
    honor_labels: true
    static_configs:
    - targets:
      - 'opentelemetrycollector:8888'
      - 'opentelemetrycollector:8889'
