using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Shopway.SourceGenerator.Base;
using Shopway.SourceGenerator.Base.Utilities;
using System.Collections.Immutable;
using System.Text;
using static Shopway.SourceGenerator.Base.Utilities.Constants;

namespace Shopway.Tests.SourceGenerator.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class UnitTestTraitsGenerator() : IncrementalGeneratorBase<UnitTestTraitsToGenerateEntry>(RegisterSourceProvider, Generate)
{
    private const string GenerateTraitsAttributeMetadataName = "System.GenerateUnitTestTraitsAttribute";
    private const string GenerateTraitsAttributeFileName = "GenerateUnitTestTraitsAttribute.g.cs";

    private const string UnitTestGeneratedTraitsFileName = "UnitTestGeneratedTraits";

    public const string GenerateTraitsAttribute = Header + """

namespace System;

/// <summary>
/// Add to AssemblyReference in the test assembly to generate Unit Test Traits
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the dr-marek-jaskula source generator.")]
public class GenerateUnitTestTraitsAttribute : global::System.Attribute;
""";

    private static IncrementalValuesProvider<UnitTestTraitsToGenerateEntry> RegisterSourceProvider(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource
        (
            GenerateTraitsAttributeFileName,
            SourceText.From(GenerateTraitsAttribute, Encoding.UTF8))
        );

        return context
            .SyntaxProvider
            .ForAttributeWithMetadataName(GenerateTraitsAttributeMetadataName, Selectors.IsClass, MapToTraitsToGenerate)
            .Where(x => x != UnitTestTraitsToGenerateEntry.None);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<UnitTestTraitsToGenerateEntry> traitsToGenerateEntries)
    {
        foreach (var traitsToGenerateEntry in traitsToGenerateEntries)
        {
            StringBuilder sb = new();
            var result = traitsToGenerateEntry.Generate(sb);
            context.AddSource(UnitTestGeneratedTraitsFileName + GeneratedFileExtension, SourceText.From(result, Encoding.UTF8));
        }
    }

    private static UnitTestTraitsToGenerateEntry MapToTraitsToGenerate(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol entitySymbol)
        {
            return UnitTestTraitsToGenerateEntry.None;
        }

        cancellationToken.ThrowIfCancellationRequested();

        string @namespace = entitySymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : entitySymbol.ContainingNamespace.ToString();

        return new(@namespace);
    }
}
