using Shopway.SourceGenerator.Generators;
using Shopway.SourceGenerator.Tests.Unit.Utilities;
using static Shopway.SourceGenerator.Tests.Unit.Utilities.Constants;

namespace Shopway.SourceGenerator.Tests.Unit.GeneratorTests;

[Trait(nameof(UnitTest), UnitTest.SourceGenerator)]
public sealed class EntityIdConverterGeneratorTests
{
    private readonly EntityIdConverterGenerator _entityIdConverterGenerator;

    public EntityIdConverterGeneratorTests()
    {
        _entityIdConverterGenerator = new EntityIdConverterGenerator();
    }

    [Fact]
    public void EntityIdConverterGenerator_ShouldGenerateEntityIdConverterAttribute()
    {
        //Act
        var actualResult = _entityIdConverterGenerator.Generate(string.Empty);

        //Assert
        actualResult.Should().Be(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the dr-marek-jaskula source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace System;

/// <summary>
/// Add to entity configurations to indicate that entity id converter should be generated
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = ""Generated by the dr-marek-jaskula source generator."")]
public class GenerateEntityIdConverterAttribute : global::System.Attribute
{
    public required string IdName;
    public required string IdNamespace;
}");
    }

    [Fact]
    public void EntityIdConverterGenerator_ShouldGenerateEntityIdConverter()
    {
        //Arrange
        (string input, string output) = GetEntityToGenerateId();

        //Act
        var actualResult = _entityIdConverterGenerator.Generate(input);

        //Asset
        actualResult.Should().Be(output);
    }

    private static (string input, string output) GetEntityToGenerateId()
    {
        var input = """
        using System;
        using OtherNamespace.ProductIdNamespace;
        
        namespace MyNamespace
        {
            [GenerateEntityIdConverter(IdName = nameof(ProductId), IdNamespace = "OtherNamespace.ProductIdNamespace"]
            public sealed class Product;
        }
        
        namespace OtherNamespace.ProductIdNamespace
        {
            public readonly record struct ProductId;
        }
        """;

        var output = """
         //------------------------------------------------------------------------------
         // <auto-generated>
         //     This code was generated by the dr-marek-jaskula source generator
         //
         //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
         // </auto-generated>
         //------------------------------------------------------------------------------

         #nullable enable

         using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
         using OtherNamespace.ProductIdNamespace;

         namespace MyNamespace;

         public sealed class ProductIdConverter : ValueConverter<ProductId, string>
         {
             public ProductIdConverter() : base(id => id.Value.ToString(), ulid => ProductId.Create(Ulid.Parse(ulid))) { }
         }

         """;

        return (input, output);
    }
}