namespace Shopway.SourceGenerator.Base.Utilities;

public static class Constants
{
    public const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the dr-marek-jaskula source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
";

    public const string GeneratedFileExtension = ".g.cs";

    public const string IdName = nameof(IdName);
    public const string IdNamespace = nameof(IdNamespace);

    public const string EnumName = nameof(EnumName);
    public const string EnumNamespace = nameof(EnumNamespace);

    public static class TrackingNames
    {
        public const string InitialValues = nameof(InitialValues);
        public const string NotNullValues = nameof(NotNullValues);
    }
}
